[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "your-project"
version = "0.1.0"
description = ""

[dependencies]
python = "^3.8"
aiohttp = "^3.7.4"